#!/bin/bash
#
# AUTHOR: Esteban Sannin ----> Stefano Viola
# VERSION: 1.0 - 20 Aug 2009 10:54
# LICENZE: GPL
#
#
function usage {
    echo -e "\n\n\n"
    echo -e "\t \t \t GPG Key - Registra comodamente le tue chiavi GPG"
    echo -e "\t \t \t Author: Esteban Sannin ---> Stefano Viola"
    echo -e "\n\n\n"
    echo -e "\t \t Example for Usage:"
    echo -e "\t \t gpgkey [option]"
    echo -e "\t -g"
    echo -e "\t \t Start with gui interface\n"
    echo -e "\t -h"
    echo -e "\t\t This help text\n"
    echo -e "\t -i"
    echo -e "\t \t Run a text dialog\n"
    echo -e "\t -k"
    echo -e "\t \t For direct add key."
    echo -e "\t \t Example for usage:"
    echo -e "\t \t gpgkey -k [ yourkey ] \n \n \n"
    echo "enjoy Esteban Sannin!"
    printf '\n\n\n'
    exit 0
}
function gui {
    key=`zenity --title "GPG Key Register" --entry --text="Insert key" --width=430`
    if [ "$key" = "" ]
    then 
	zenity --info --text="Requested Annulled" --title "GPG Key Register"
	exit 1
    else
    gpg --keyserver keyserver.ubuntu.com --recv $key
    gpg --export --armor $key 
    gksudo apt-key add -
    fi 
}

function directkey {
    echo "Direct key insert"
    gpg --keyserver keyserver.ubuntu.com --recv $2
    gpg --export --armor $2 
    sudo apt-key add -
}
function interactive {
    ans="y"
    while [ "$ans" = y ]
    do
	echo -n "Insert the key GPG: "
	read key
	gpg --keyserver keyserver.ubuntu.com --recv $key
	gpg --export --armor $key | sudo apt-key add -
	echo -n "Do you want to record another key?(y/n): "
	read ans
    done
    exit 0
}

function console {
    case $1 in
	"-g" ) gui;;
	"-i" ) interactive;;
	"-h" ) usage;;
	"-k" ) directkey;;
	* ) usage;;
    esac
}
console "$1"